In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
import torch.nn as nn

In [ ]:
import torch

In [ ]:
#Input tensor of 3 features

X = torch.tensor([0.3474, 0.4547, -0.2356])

#X : input tensor

print(X.dtype)
print(X.shape)

torch.float32
torch.Size([3])


In [ ]:
#Linear : W et b
linear_layer = nn.Linear(in_features=3, out_features=2)

#Y : output tensor (sa dimension est out = 2)
Y = linear_layer(X)

print(Y)

tensor([-0.1021, -0.6869], grad_fn=<AddBackward0>)


In [ ]:
#Si par exemple X est une matrice de m lignes (m donnees) y comportera m lignes

data = torch.randn(7, 3)
X = torch.tensor(data)

print(X, '\n')

linear_layer = nn.Linear(in_features=3, out_features=2)
Y = linear_layer(X)

print(Y)

In [ ]:
#Affichage des W et b
print(linear_layer.weight.shape)
print(linear_layer.bias.shape)

torch.Size([2, 3])
torch.Size([2])


In [ ]:
print(Y, '\n\n')

print(X @ linear_layer.weight.T + linear_layer.bias)

tensor([[-0.1120, -1.1609],
        [ 0.7992, -2.2950],
        [-0.7487,  0.0052],
        [-0.6474,  0.2106],
        [-0.2446, -0.3962],
        [-0.1208, -0.2796],
        [-0.7647,  0.0067]], grad_fn=<AddmmBackward0>) 


tensor([[-0.1120, -1.1609],
        [ 0.7992, -2.2950],
        [-0.7487,  0.0052],
        [-0.6474,  0.2106],
        [-0.2446, -0.3962],
        [-0.1208, -0.2796],
        [-0.7647,  0.0067]], grad_fn=<AddBackward0>)


In [ ]:
#Multiple Layers
#Network creation

model = nn.Sequential(
    nn.Linear(10, 18),
    nn.Linear(18, 20),
    nn.Linear(20, 5)
)

data = torch.randn(1, 10)
X = torch.tensor(data)

print(X)

#Pass X into the model
Y = model(X)

print(Y.shape)
print(Y)

tensor([[ 2.3078,  3.2625,  0.4936, -2.1576, -0.2488, -1.1878,  0.9181, -1.3464,
         -1.4580,  0.7794]])
torch.Size([1, 5])
tensor([[ 0.2322,  0.2087, -0.0365, -0.3860, -0.4498]],
       grad_fn=<AddmmBackward0>)
